##############################################################################################################################################################
##								                           	<<<<  DOOR SENSOR CARD >>>> 
##############################################################################################################################################################


        - type: 'custom:swiss-army-knife-card'
          entities:
            - entity: binary_sensor.wc_deur_access_control_window_door_is_open
              name: 'WC Deur'
              area: 'Hal'
            - entity: binary_sensor.wc_deur_access_control_window_door_is_open
              secondary_info: last_changed
              format: relative
              
            - entity: sensor.wc_deur_battery_level
              name: Battery
              icon: mdi:battery

          # Define aspect ratio as square
          aspectratio: 1/1

          disable_card: false

          dev:
            debug: false
            
          layout:
            styles:
              card:
              toolsets:
              
            toolsets:
              # ================================================================
              - toolset: square-state
                position:
                  cx: 50
                  cy: 50
                tools:
                  # Background used for active / inactive card
                  # default settings in user-css-definitions.yaml see https://swiss-army-knife-card-manual.amoebelabs.com/basics/styling/classes/
                  # ------------------------------------------------------------
                  - type: rectex
                    position:
                      cx: 50
                      cy: 50
                      width: 100
                      height: 100
                      radius:
                        top: 0
                        bottom: 0
                    entity_index: 0
                    animations:
                      - state: 'on'
                        classes:
                          rectex:
                            sak-card--on: true
                      - state: 'off'
                        classes:
                          rectex:
                            sak-card--off: true

                  # State rectangle at the top of the card. Colors with the state
                  # ------------------------------------------------------------
                  - type: rectex
                    position:
                      cx: 50
                      cy: 2.5
                      width: 90
                      height: 5
                      radius:
                        top: 0
                        bottom: 2
                    entity_index: 0
                    animations:
                      - state: 'on'
                        classes:
                          rectex:
                            sak-alert2--active: true
                      - state: 'off'
                        classes:
                          rectex:
                            sak-alert2--clear: true

                  # ------------------------------------------------------------
                  - type: icon
                    position:
                      cx: 25
                      cy: 25
                      align: center
                      icon_size: 30
                    entity_index: 0
                    # Define colors for the icon depending on the state
                    # Note that we have to define both on and off states, as for some reason
                    # the default styling (in case of 'off' state keeps the color of the 'on'
                    # state (unexpected...)
                    #
                    # The icon animation ONLY works in Safari. This is due to the fact that
                    # Safari has a different render path than Chrome. This will be fixed 
                    # in the future of course ;-)
                    animations:
                      - state: 'on'
                        styles:
                          icon:
                            fill: var(--theme-sys-ha-primary-text-color)
                            animation: jello 2s ease-in-out both
                      - state: 'off'
                        styles:
                          icon:
                            fill: var(--theme-sys-ha-disabled-text-color)
                    styles:
                      icon:
                        fill: var(--theme-sys-ha-primary-text-color)
                  # ------------------------------------------------------------
                  - type: icon
                    icon: mdi:battery
                    position:
                      cx: 62
                      cy: 25
                      align: center
                      icon_size: 10
                    entity_index: 2
                    styles:
                      icon:
                        fill: var(--primary-text-color)
                  # ------------------------------------------------------------
                  - type: state
                    position:
                      cx: 75
                      cy: 25
                    entity_index: 2
                    styles:
                      state:
                        text-anchor: middle
                        font-size: 7em
                        font-weight: 700
                        fill: var(--primary-text-color)
                      uom:
                        fill: var(--primary-text-color)
                        font-weight: 700
                  # ------------------------------------------------------------
                  - type: name
                    position:
                      cx: 10
                      cy: 55
                    entity_index: 0
                    classes:
                      name:
                        homekit-name__name: true

                  # ------------------------------------------------------------
                  - type: area
                    position:
                      cx: 10
                      cy: 70
                    entity_index: 0
                    classes:
                      area:
                        homekit-area__area: true

                  # ------------------------------------------------------------
                  - type: state
                    position:
                      cx: 10
                      cy: 85
                    entity_index: 1
                    styles:
                      state:
                        text-anchor: start
                        font-size: 8em
                        font-weight: 700
                        fill: var(--theme-sys-ha-primary-text-color)
                      uom:
                        fill: var(--theme-sys-ha-primary-text-color)
                        font-weight: 700

##############################################################################################################################################################
##								                    	<<<<<  END DOOR SENSOR CARD   >>>>>
##############################################################################################################################################################