################################################################################################################################
###                                           Wakeup light Card
##################################################################################################################################

    - type: 'custom:swiss-army-knife-card'
      entities:
        - entity: input_boolean.wakeup_enabled_tuin
          name: 'WakeUp Light Nikki'
        - entity: input_boolean.wakeup_weekend_tuin
          name: 'Enable Weekend'
        - entity: input_datetime.wakeup_time_tuin
          name: 'Time'
      # Define aspect ratio
      aspectratio: 3/1                          # Card is 300x100 grid

      layout:
        toolsets:
          # ================================================================
          - toolset: badge-background
            position:
              cx: 150
              cy: 50
            tools:
              - type: badge
                position:
                  cx: 50
                  cy: 50
                  height: 100
                  width: 300
                  ratio: 25
                  radius: 5
                  divider: 30
                entity_index: 0
                animations:
                  - state: 'on'               # Animate for state ON
                    styles:
                      left:
                        fill: var(--theme-sys-color-primary)
                  - state: 'off'        # Animate for state OFF
                    styles:
                      left:
                        fill: var(--theme-sys-elevation-surface-neutral4)
                styles:
                  left:
                    fill: grey
                  right:
                    fill: none                  # Show background
                    pointer-events: none        # Disable user interaction

          # ================================================================
          - toolset: column-icon
            position:
              cx: 50                           # On 12.5% f width
              cy: 50
            tools:
              # ------------------------------------------------------------
              - type: icon
                position:
                  cx: 50
                  cy: 50
                  align: center
                  icon_size: 40
                entity_index: 0
                #icon: 'mdi:light'
                animations:
                  - state: 'on'
                    icon: 'mdi:light'
                    styles:
                      icon:
                        animation: heartBeat 8s infinite
                        fill: var(--primary-text-color)
                  - state: 'off' 
                    icon: 'mdi:light'
                    styles:
                      icon:
                        # fill: var(--theme-sys-color-on-secondary-container)
                        fill: var(--theme-sys-color-secondary)
                styles:
                  icon:
                    fill: var(--primary-background-color)
                    opacity: 0.9
                    pointer-events: none        # Disable user interaction
                    # transition: fill 1s ease
           # ================================================================
           # Switch 1 On of Wake up Light
           # ================================================================
          - toolset: switch
            position:
              cx: 37.5                           # On 1/3 of card width
              cy: 50
              #scale: 2
            tools:
              # ------------------------------------------------------------
              - type: switch
                position:
                  cx: 65
                  cy: 85
                  orientation: 'horizontal'
                  track:
                    width: 45
                    height: 20
                    radius: 2.5
                  thumb:
                    width: 15
                    height: 12
                    radius: 2.5
                    offset: 4.5
                entity_index: 0
                user_actions:
                  tap_action:
                    haptic: switch
                    actions:
                      - action: call-service
                        service: input_boolean.toggle
                styles:
                  track:
                    --switch-checked-track-color: var(--primary-background-color)
                    --switch-unchecked-track-color: var(--theme-sys-color-secondary)
                    --switch-checked-button-color: var(--primary-color)
                    --switch-unchecked-button-color: var(--primary-background-color)
                  thumb:
                    --thumb-stroke: 'var(--primary-background-color)'

           # ================================================================
           # Switch 2 Weekend On / Off
           # ================================================================
          - toolset: switch
            position:
              cx: 37.5                      # On 1/3 of card width
              cy: 50
              #scale: 2
            tools:
              # ------------------------------------------------------------
              - type: switch
                position:
                  cx: 65
                  cy: 15
                  orientation: 'horizontal'
                  track:
                    width: 45
                    height: 20
                    radius: 2.5
                  thumb:
                    width: 15
                    height: 12
                    radius: 2.5
                    offset: 4.5
                entity_index: 1
                user_actions:
                  tap_action:
                    haptic: switch
                    actions:
                      - action: call-service
                        service: input_boolean.toggle
                styles:
                  track:
                    --switch-checked-track-color: var(--primary-background-color)
                    --switch-unchecked-track-color: var(--theme-sys-color-secondary)
                    --switch-checked-button-color: var(--primary-color)
                    --switch-unchecked-button-color: var(--primary-background-color)
                  thumb:
                    --thumb-stroke: 'var(--primary-background-color)'

          # ================================================================
          - toolset: column-name
            position:
              cx: 100                   # Left part = 75, so 75+(300-75)/2
              cy: 50
            tools:
              # ------------------------------------------------------------
              - type: name
                position:
                  cx: 50
                  cy: 50
                entity_index: 0
                styles:
                  name:
                    text-anchor: start
                    font-size: 20em
                    font-weight: 600
                    opacity: 1
              # ------------------------------------------------------------
              - type: state
                position:
                  cx: 50
                  cy: 80
                entity_index: 2
                show:
                  uom: none
                styles:
                  state:
                    text-anchor: start
                    font-size: 16em
                    font-weight: 500
                    opacity: 0.7
              # ------------------------------------------------------------
              # Enable weekend
              # ------------------------------------------------------------
              - type: name
                position:
                  cx: 130
                  cy: 20
                entity_index: 1
                styles:
                  name:
                    text-anchor: start
                    font-size: 14em
                    font-weight: 500
                    opacity: 1
              # ------------------------------------------------------------
              - type: state
                position:
                  cx: 50
                  cy: 20
                entity_index: 1
                show:
                  uom: none
                styles:
                  state:
                    text-anchor: start
                    font-size: 18em
                    font-weight: 600
                    opacity: 0.8
                    
################################################################################################################################
###                                         END   Wakeup light Card
##################################################################################################################################